### ISSUE TITLE
ArgumentOutOfRangeException, parameter "top"

### ISSUE THREAD

**Issue by fubar-coder** [petabridge/petabridge.cmd-issues#35]
```text
[ERROR][09.10.2020 00:57:52][Thread 0013][akka://pbmClient/user/console] The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 30.
Cause: System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 30.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Petabridge.Cmd.Client.Handler.ConsoleHandlerActor.ClearCurrentLines(Int32 startingLine, Int32 currentLine) in D:\a\1\s\src\Petabridge.Cmd.Client\Handler\ConsoleHandlerActor.cs:line 297
   at Petabridge.Cmd.Client.Handler.ConsoleHandlerActor.<Reading>b__20_0(Read _) in D:\a\1\s\src\Petabridge.Cmd.Client\Handler\ConsoleHandlerActor.cs:line 158
   at lambda_method(Closure , Object , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`3.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.<>c__DisplayClass11_0.<Become>b__0(Object m)
   at Akka.Actor.ActorCell.<>c__DisplayClass114_0.<Akka.Actor.IUntypedActorContext.Become>b__0(Object m)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

Tool version 0.8.0
Terminal: Windows Terminal 1.3.2651.0

What I did:
* Enter "cluster " (with a space at the end)
* Press TAB key
* Press BACKSPACE key

**Comment by IgorFedchenko** [comment]
I was able to reproduce this in Windows Terminal too (cmd and powershell works fine).

**Comment by IgorFedchenko** [comment]
Fixed with PR attached
